name: Recursive Descent Interpreter Tests

on: [pull_request]

jobs: 
  test: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set execute permissions for test scripts
        run: chmod +x tester.sh

      - name: Run test cases
        run: |
          output=$(./tester.sh)

          if echo "$output" | grep -q "Print looks good"; then
            echo "✅ All tests ran successfully"
          else
            echo "❌ Some tests failed!"
            exit 1
          fi
